// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uboqhbjqiiyzbeuhpcqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVib3FoYmpxaWl5emJldWhwY3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzAyMDcsImV4cCI6MjA2MDYwNjIwN30.YVEBjlv_BiGJZAWPi-jk9wqKAEfmeSkG4MlQebDst-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);